.include "macro.inc"

.section .bss

/* Generated by spimdisasm 1.26.0 */

dlabel D_80038860
/* 39460 80038860 */ .space 0x21B0

dlabel D_8003AA10
/* 3B610 8003AA10 */ .space 0x2000

dlabel D_8003CA10
/* 3D610 8003CA10 */ .space 0x80

dlabel D_8003CA90
/* 3D690 8003CA90 */ .space 0x18

dlabel D_8003CAA8
/* 3D6A8 8003CAA8 */ .space 0x08

dlabel D_8003CAB0
/* 3D6B0 8003CAB0 */ .space 0x18

dlabel D_8003CAC8
/* 3D6C8 8003CAC8 */ .space 0x08

dlabel D_8003CAD0
/* 3D6D0 8003CAD0 */ .space 0x18

dlabel D_8003CAE8
/* 3D6E8 8003CAE8 */ .space 0x27C

dlabel D_8003CD64
/* 3D964 8003CD64 */ .space 0x0C

dlabel D_8003CD70
/* 3D970 8003CD70 */ .space 0x2008

dlabel D_8003ED78
/* 3F978 8003ED78 */ .space 0x08

dlabel D_8003ED80
/* 3F980 8003ED80 */ .space 0x14

dlabel D_8003ED94
/* 3F994 8003ED94 */ .space 0x6C

dlabel D_8003EE00
/* 3FA00 8003EE00 */ .space 0x10

dlabel D_8003EE10
/* 3FA10 8003EE10 */ .space 0x04

dlabel D_8003EE14
/* 3FA14 8003EE14 */ .space 0x04

dlabel D_8003EE18
/* 3FA18 8003EE18 */ .space 0x08

dlabel D_8003EE20
/* 3FA20 8003EE20 */ .space 0x21B0

dlabel D_80040FD0
/* 41BD0 80040FD0 */ .space 0x08

dlabel D_80040FD8
/* 41BD8 80040FD8 */ .space 0x18

dlabel D_80040FF0
/* 41BF0 80040FF0 */ .space 0x40

dlabel D_80041030
/* 41C30 80041030 */ .space 0x18

dlabel D_80041048
/* 41C48 80041048 */ .space 0x08

dlabel D_80041050
/* 41C50 80041050 */ .space 0x18

dlabel D_80041068
/* 41C68 80041068 */ .space 0x04

dlabel D_8004106C
/* 41C6C 8004106C */ .space 0x04

dlabel D_80041070
/* 41C70 80041070 */ .space 0x08

dlabel D_80041078
/* 41C78 80041078 */ .space 0x50

dlabel D_800410C8
/* 41CC8 800410C8 */ .space 0x08

dlabel D_800410D0
/* 41CD0 800410D0 */ .space 0x04

dlabel D_800410D4
/* 41CD4 800410D4 */ .space 0x7FC

dlabel D_800418D0
/* 424D0 800418D0 */ .space 0x02

dlabel D_800418D2
/* 424D2 800418D2 */ .space 0x06

dlabel D_800418D8
/* 424D8 800418D8 */ .space 0x200

dlabel D_80041AD8
/* 426D8 80041AD8 */ .space 0x200

dlabel D_80041CD8
/* 428D8 80041CD8 */ .space 0x02

dlabel D_80041CDA
/* 428DA 80041CDA */ .space 0x06

dlabel D_80041CE0
/* 428E0 80041CE0 */ .space 0x1000

dlabel D_80042CE0
/* 438E0 80042CE0 */ .space 0x04

dlabel D_80042CE4
/* 438E4 80042CE4 */ .space 0x04

dlabel D_80042CE8
/* 438E8 80042CE8 */ .space 0x04

dlabel D_80042CEC
/* 438EC 80042CEC */ .space 0x01

dlabel D_80042CED
/* 438ED 80042CED */ .space 0x03

dlabel D_80042CF0
/* 438F0 80042CF0 */ .space 0x40

dlabel D_80042D30
/* 43930 80042D30 */ .space 0x21B0

dlabel D_80044EE0
/* 45AE0 80044EE0 */ .space 0x10

dlabel D_80044EF0
/* 45AF0 80044EF0 */ .space 0x50

dlabel D_80044F40
/* 45B40 80044F40 */ .space 0x28

dlabel D_80044F68
/* 45B68 80044F68 */ .space 0x20

dlabel D_80044F88
/* 45B88 80044F88 */ .space 0x0C

dlabel D_80044F94
/* 45B94 80044F94 */ .space 0x04

dlabel D_80044F98
/* 45B98 80044F98 */ .space 0x04

dlabel D_80044F9C
/* 45B9C 80044F9C */ .space 0x04

dlabel D_80044FA0
/* 45BA0 80044FA0 */ .space 0x08

dlabel D_80044FA8
/* 45BA8 80044FA8 */ .space 0x20

dlabel D_80044FC8
/* 45BC8 80044FC8 */ .space 0x80

dlabel D_80045048
/* 45C48 80045048 */ .space 0xF8

dlabel D_80045140
/* 45D40 80045140 */ .space 0x08

dlabel D_80045148
/* 45D48 80045148 */ .space 0x54

dlabel D_8004519C
/* 45D9C 8004519C */ .space 0x04

dlabel D_800451A0
/* 45DA0 800451A0 */ .space 0x04

dlabel D_800451A4
/* 45DA4 800451A4 */ .space 0x04

dlabel D_800451A8
/* 45DA8 800451A8 */ .space 0x18

dlabel D_800451C0
/* 45DC0 800451C0 */ .space 0x180

dlabel D_80045340
/* 45F40 80045340 */ .space 0x40

dlabel D_80045380
/* 45F80 80045380 */ .space 0x10

dlabel D_80045390
/* 45F90 80045390 */ .space 0x14

dlabel D_800453A4
/* 45FA4 800453A4 */ .space 0x26C

dlabel D_80045610
/* 46210 80045610 */ .space 0x18

dlabel D_80045628
/* 46228 80045628 */ .space 0x20

dlabel D_80045648
/* 46248 80045648 */ .space 0x04

dlabel D_8004564C
/* 4624C 8004564C */ .space 0x04

dlabel D_80045650
/* 46250 80045650 */ .space 0x08

dlabel D_80045658
/* 46258 80045658 */ .space 0x21B0

dlabel D_80047808
/* 48408 80047808 */ .space 0x18

dlabel D_80047820
/* 48420 80047820 */ .space 0x50

dlabel D_80047870
/* 48470 80047870 */ .space 0x04

dlabel D_80047874
/* 48474 80047874 */ .space 0x04

dlabel D_80047878
/* 48478 80047878 */ .space 0x08

dlabel D_80047880
/* 48480 80047880 */ .space 0x08

dlabel D_80047888
/* 48488 80047888 */ .space 0x08

dlabel D_80047890
/* 48490 80047890 */ .space 0x08

dlabel D_80047898
/* 48498 80047898 */ .space 0x80

dlabel D_80047918
/* 48518 80047918 */ .space 0x18

dlabel D_80047930
/* 48530 80047930 */ .space 0x08

dlabel D_80047938
/* 48538 80047938 */ .space 0x18

dlabel D_80047950
/* 48550 80047950 */ .space 0x0C

dlabel D_8004795C
/* 4855C 8004795C */ .space 0x04

dlabel D_80047960
/* 48560 80047960 */ .space 0x10

dlabel D_80047970
/* 48570 80047970 */ .space 0x04

dlabel D_80047974
/* 48574 80047974 */ .space 0x0C

dlabel D_80047980
/* 48580 80047980 */ .space 0x18

dlabel D_80047998
/* 48598 80047998 */ .space 0x08

dlabel D_800479A0
/* 485A0 800479A0 */ .space 0x10

dlabel D_800479B0
/* 485B0 800479B0 */ .space 0x18

dlabel D_800479C8
/* 485C8 800479C8 */ .space 0x18

dlabel D_800479E0
/* 485E0 800479E0 */ .space 0x1A0

dlabel D_80047B80
/* 48780 80047B80 */ .space 0x01

dlabel D_80047B81
/* 48781 80047B81 */ .space 0x01

dlabel D_80047B82
/* 48782 80047B82 */ .space 0x01

dlabel D_80047B83
/* 48783 80047B83 */ .space 0x01

dlabel D_80047B84
/* 48784 80047B84 */ .space 0x01

dlabel D_80047B85
/* 48785 80047B85 */ .space 0x01

dlabel D_80047B86
/* 48786 80047B86 */ .space 0x01

dlabel D_80047B87
/* 48787 80047B87 */ .space 0x01

dlabel D_80047B88
/* 48788 80047B88 */ .space 0x01

dlabel D_80047B89
/* 48789 80047B89 */ .space 0x01

dlabel D_80047B8A
/* 4878A 80047B8A */ .space 0x01

dlabel D_80047B8B
/* 4878B 80047B8B */ .space 0x01

dlabel D_80047B8C
/* 4878C 80047B8C */ .space 0x01

dlabel D_80047B8D
/* 4878D 80047B8D */ .space 0x01

dlabel D_80047B8E
/* 4878E 80047B8E */ .space 0x01

dlabel D_80047B8F
/* 4878F 80047B8F */ .space 0x01

dlabel D_80047B90
/* 48790 80047B90 */ .space 0x30

dlabel D_80047BC0
/* 487C0 80047BC0 */ .space 0x40

dlabel D_80047C00
/* 48800 80047C00 */ .space 0x40

dlabel D_80047C40
/* 48840 80047C40 */ .space 0x08

dlabel D_80047C48
/* 48848 80047C48 */ .space 0x10

dlabel D_80047C58
/* 48858 80047C58 */ .space 0x02

dlabel D_80047C5A
/* 4885A 80047C5A */ .space 0x02

dlabel D_80047C5C
/* 4885C 80047C5C */ .space 0x54

dlabel D_80047CB0
/* 488B0 80047CB0 */ .space 0x30

dlabel D_80047CE0
/* 488E0 80047CE0 */ .space 0x1A8

dlabel D_80047E88
/* 48A88 80047E88 */ .space 0x04

dlabel D_80047E8C
/* 48A8C 80047E8C */ .space 0x04

dlabel D_80047E90
/* 48A90 80047E90 */ .space 0x10

dlabel D_80047EA0
/* 48AA0 80047EA0 */ .space 0x2C80

dlabel D_8004AB20
/* 4B720 8004AB20 */ .space 0x01

dlabel D_8004AB21
/* 4B721 8004AB21 */ .space 0x1F

dlabel D_8004AB40
/* 4B740 8004AB40 */ .space 0x01

dlabel D_8004AB41
/* 4B741 8004AB41 */ .space 0x1F

dlabel D_8004AB60
/* 4B760 8004AB60 */ .space 0x01

dlabel D_8004AB61
/* 4B761 8004AB61 */ .space 0x5BF

dlabel D_8004B120
/* 4BD20 8004B120 */ .space 0x40

dlabel D_8004B160
/* 4BD60 8004B160 */ .space 0x580

dlabel D_8004B6E0
/* 4C2E0 8004B6E0 */ .space 0x0C

dlabel D_8004B6EC
/* 4C2EC 8004B6EC */ .space 0xE4

dlabel D_8004B7D0
/* 4C3D0 8004B7D0 */ .space 0x28

dlabel D_8004B7F8
/* 4C3F8 8004B7F8 */ .space 0x0C

dlabel D_8004B804
/* 4C404 8004B804 */ .space 0x108

dlabel D_8004B90C
/* 4C50C 8004B90C */ .space 0x04

dlabel D_8004B910
/* 4C510 8004B910 */ .space 0x04

dlabel D_8004B914
/* 4C514 8004B914 */ .space 0x04

dlabel D_8004B918
/* 4C518 8004B918 */ .space 0x08

dlabel D_8004B920
/* 4C520 8004B920 */ .space 0x04

dlabel D_8004B924
/* 4C524 8004B924 */ .space 0x04

dlabel D_8004B928
/* 4C528 8004B928 */ .space 0x04

dlabel D_8004B92C
/* 4C52C 8004B92C */ .space 0x04

dlabel D_8004B930
/* 4C530 8004B930 */ .space 0x14

dlabel D_8004B944
/* 4C544 8004B944 */ .space 0x4EFC

dlabel D_80050840
/* 51440 80050840 */ .space 0xE60

dlabel D_800516A0
/* 522A0 800516A0 */ .space 0x20

dlabel D_800516C0
/* 522C0 800516C0 */ .space 0xE60

dlabel D_80052520
/* 53120 80052520 */ .space 0x4F10

dlabel D_80057430
/* 58030 80057430 */ .space 0xA0

dlabel D_800574D0
/* 580D0 800574D0 */ .space 0x04

dlabel D_800574D4
/* 580D4 800574D4 */ .space 0x24

dlabel D_800574F8
/* 580F8 800574F8 */ .space 0x04

dlabel D_800574FC
/* 580FC 800574FC */ .space 0x24

dlabel D_80057520
/* 58120 80057520 */ .space 0x08

dlabel D_80057528
/* 58128 80057528 */ .space 0x18

dlabel D_80057540
/* 58140 80057540 */ .space 0x08

dlabel D_80057548
/* 58148 80057548 */ .space 0x08

dlabel D_80057550
/* 58150 80057550 */ .space 0x04

dlabel D_80057554
/* 58154 80057554 */ .space 0x04

dlabel D_80057558
/* 58158 80057558 */ .space 0x170

dlabel D_800576C8
/* 582C8 800576C8 */ .space 0x01

dlabel D_800576C9
/* 582C9 800576C9 */ .space 0x01

dlabel D_800576CA
/* 582CA 800576CA */ .space 0x01

dlabel D_800576CB
/* 582CB 800576CB */ .space 0x01

dlabel D_800576CC
/* 582CC 800576CC */ .space 0x01

dlabel D_800576CD
/* 582CD 800576CD */ .space 0x01

dlabel D_800576CE
/* 582CE 800576CE */ .space 0x01

dlabel D_800576CF
/* 582CF 800576CF */ .space 0x01

dlabel D_800576D0
/* 582D0 800576D0 */ .space 0x01

dlabel D_800576D1
/* 582D1 800576D1 */ .space 0x01

dlabel D_800576D2
/* 582D2 800576D2 */ .space 0x01

dlabel D_800576D3
/* 582D3 800576D3 */ .space 0x01

dlabel D_800576D4
/* 582D4 800576D4 */ .space 0x01

dlabel D_800576D5
/* 582D5 800576D5 */ .space 0x01

dlabel D_800576D6
/* 582D6 800576D6 */ .space 0x01

dlabel D_800576D7
/* 582D7 800576D7 */ .space 0x01

dlabel D_800576D8
/* 582D8 800576D8 */ .space 0x01

dlabel D_800576D9
/* 582D9 800576D9 */ .space 0x01

dlabel D_800576DA
/* 582DA 800576DA */ .space 0x01

dlabel D_800576DB
/* 582DB 800576DB */ .space 0x05

dlabel D_800576E0
/* 582E0 800576E0 */ .space 0xB80

dlabel D_80058260
/* 58E60 80058260 */ .space 0x1C

dlabel D_8005827C
/* 58E7C 8005827C */ .space 0x354

dlabel D_800585D0
/* 591D0 800585D0 */ .space 0xA0

dlabel D_80058670
/* 59270 80058670 */ .space 0x28

dlabel D_80058698
/* 59298 80058698 */ .space 0x28

dlabel D_800586C0
/* 592C0 800586C0 */ .space 0x190

dlabel D_80058850
/* 59450 80058850 */ .space 0x28

dlabel D_80058878
/* 59478 80058878 */ .space 0x08

dlabel D_80058880
/* 59480 80058880 */ .space 0x10

dlabel D_80058890
/* 59490 80058890 */ .space 0x41B0

dlabel D_8005CA40
/* 5D640 8005CA40 */ .space 0x10

dlabel D_8005CA50
/* 5D650 8005CA50 */ .space 0x1B0

dlabel D_8005CC00
/* 5D800 8005CC00 */ .space 0x1000

dlabel D_8005DC00
/* 5E800 8005DC00 */ .space 0x18

dlabel D_8005DC18
/* 5E818 8005DC18 */ .space 0x08

dlabel D_8005DC20
/* 5E820 8005DC20 */ .space 0x04

dlabel D_8005DC24
/* 5E824 8005DC24 */ .space 0x01

dlabel D_8005DC25
/* 5E825 8005DC25 */ .space 0x01

dlabel D_8005DC26
/* 5E826 8005DC26 */ .space 0x01

dlabel D_8005DC27
/* 5E827 8005DC27 */ .space 0x01

dlabel D_8005DC28
/* 5E828 8005DC28 */ .space 0x01

dlabel D_8005DC29
/* 5E829 8005DC29 */ .space 0x03

dlabel D_8005DC2C
/* 5E82C 8005DC2C */ .space 0x74

dlabel D_8005DCA0
/* 5E8A0 8005DCA0 */ .space 0x1B0

dlabel D_8005DE50
/* 5EA50 8005DE50 */ .space 0x1000

dlabel D_8005EE50
/* 5FA50 8005EE50 */ .space 0x18

dlabel D_8005EE68
/* 5FA68 8005EE68 */ .space 0x18

dlabel D_8005EE80
/* 5FA80 8005EE80 */ .space 0x02

dlabel D_8005EE82
/* 5FA82 8005EE82 */ .space 0x02

dlabel D_8005EE84
/* 5FA84 8005EE84 */ .space 0x14

dlabel D_8005EE98
/* 5FA98 8005EE98 */ .space 0x02

dlabel D_8005EE9A
/* 5FA9A 8005EE9A */ .space 0x02

dlabel D_8005EE9C
/* 5FA9C 8005EE9C */ .space 0x14

dlabel D_8005EEB0
/* 5FAB0 8005EEB0 */ .space 0x10

dlabel D_8005EEC0
/* 5FAC0 8005EEC0 */ .space 0x80

dlabel D_8005EF40
/* 5FB40 8005EF40 */ .space 0x40

dlabel D_8005EF80
/* 5FB80 8005EF80 */ .space 0x3C

dlabel D_8005EFBC
/* 5FBBC 8005EFBC */ .space 0x04

dlabel D_8005EFC0
/* 5FBC0 8005EFC0 */ .space 0x01

dlabel D_8005EFC1
/* 5FBC1 8005EFC1 */ .space 0x27

dlabel D_8005EFE8
/* 5FBE8 8005EFE8 */ .space 0x18

dlabel D_8005F000
/* 5FC00 8005F000 */ .space 0x10

dlabel D_8005F010
/* 5FC10 8005F010 */ .space 0x100

dlabel D_8005F110
/* 5FD10 8005F110 */ .space 0x100

dlabel D_8005F210
/* 5FE10 8005F210 */ .space 0x20

dlabel D_8005F230
/* 5FE30 8005F230 */ .space 0x20

dlabel D_8005F250
/* 5FE50 8005F250 */ .space 0x3C

dlabel D_8005F28C
/* 5FE8C 8005F28C */ .space 0x04

dlabel D_8005F290
/* 5FE90 8005F290 */ .space 0x10

dlabel D_8005F2A0
/* 5FEA0 8005F2A0 */ .space 0x10

dlabel D_8005F2B0
/* 5FEB0 8005F2B0 */ .space 0x04

dlabel D_8005F2B4
/* 5FEB4 8005F2B4 */ .space 0x01

dlabel D_8005F2B5
/* 5FEB5 8005F2B5 */ .space 0x01

dlabel D_8005F2B6
/* 5FEB6 8005F2B6 */ .space 0x02

dlabel D_8005F2B8
/* 5FEB8 8005F2B8 */ .space 0x01

dlabel D_8005F2B9
/* 5FEB9 8005F2B9 */ .space 0x03

dlabel D_8005F2BC
/* 5FEBC 8005F2BC */ .space 0x68

dlabel D_8005F324
/* 5FF24 8005F324 */ .space 0x0C

dlabel D_8005F330
/* 5FF30 8005F330 */ .space 0x08

dlabel D_8005F338
/* 5FF38 8005F338 */ .space 0x18

dlabel D_8005F350
/* 5FF50 8005F350 */ .space 0x20

dlabel D_8005F370
/* 5FF70 8005F370 */ .space 0x04

dlabel D_8005F374
/* 5FF74 8005F374 */ .space 0x04

dlabel D_8005F378
/* 5FF78 8005F378 */ .space 0x04

dlabel D_8005F37C
/* 5FF7C 8005F37C */ .space 0x04

dlabel D_8005F380
/* 5FF80 8005F380 */ .space 0x10

dlabel D_8005F390
/* 5FF90 8005F390 */ .space 0x08

dlabel D_8005F398
/* 5FF98 8005F398 */ .space 0x18

dlabel D_8005F3B0
/* 5FFB0 8005F3B0 */ .space 0x1B0

dlabel D_8005F560
/* 60160 8005F560 */ .space 0x1058

dlabel D_800605B8
/* 611B8 800605B8 */ .space 0x1300

dlabel D_800618B8
/* 624B8 800618B8 */ .space 0x7A7

dlabel D_8006205F
/* 62C5F 8006205F */ .space 0x81

dlabel D_800620E0
/* 62CE0 800620E0 */ .space 0x04

dlabel D_800620E4
/* 62CE4 800620E4 */ .space 0x04

dlabel D_800620E8
/* 62CE8 800620E8 */ .space 0x04

dlabel D_800620EC
/* 62CEC 800620EC */ .space 0x04

dlabel D_800620F0
/* 62CF0 800620F0 */ .space 0x04

dlabel D_800620F4
/* 62CF4 800620F4 */ .space 0x0C
